stages:
  - test
  - deploy

tests:
  stage: test
  tags:
    - dockerbr
  script:
    - echo "Running tests"
    - python --version
    - pip install pytest
    - pytest || echo "No tests yet"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

deploy_production:
  stage: deploy
  tags:
    - dockerbr
  script:
    - pip install ansible
    - New-Item -ItemType Directory -Force -Path "$env:USERPROFILE\.ssh"
    - $env:SSH_PRIVATE_KEY | Out-File -FilePath "$env:USERPROFILE\.ssh\id_ed25519_pasta" -Encoding ascii
    - ansible-playbook -i terraform/inventory.ini playbook.yml
  rules:
    - if: $CI_COMMIT_BRANCH == "9"