services:

  flask-app:
    build: .
    container_name: pasta-flask
    expose:
      - "8000"
    environment:
      - PORT=8000
    volumes:
      - pasta-data:/app/data 
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: pasta-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - flask-app
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    restart: unless-stopped
    

volumes:
  pasta-data:
  uptime-kuma-data: