server {
    listen 80;
    server_name 136.115.23.69.nip.io;
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name 136.115.23.69.nip.io;

    ssl_certificate     /etc/letsencrypt/archive/136.115.23.69.nip.io/fullchain1.pem;
    ssl_certificate_key /etc/letsencrypt/archive/136.115.23.69.nip.io/privkey1.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass       http://flask-app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }
}