---
- name: Deploy Pasta Flask + Nginx + HTTPS
  hosts: all
  become: yes
  vars:
    domain: "136.115.23.69.nip.io"
    email: "guillian_mt4@gmail.com"
    repo_dest: /home/ubuntu/pasta

  tasks:
    - name: Update system
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Docker and dependencies
      apt:
        name:
          - docker.io
          - docker-compose
          - git
          - certbot
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Stop and remove old containers
      command: docker-compose -f {{ repo_dest }}/docker-compose.yml down --remove-orphans
      args:
        chdir: "{{ repo_dest }}"
      ignore_errors: yes

    - name: Clone repo
      git:
        repo: https://github.com/Barrioth/PROJET.git
        dest: "{{ repo_dest }}"
        version: "9"
        force: yes

    - name: Get Let's Encrypt certificate (standalone)
      command: >
        certbot certonly --standalone
        -d {{ domain }}
        --email {{ email }}
        --agree-tos
        --non-interactive
      args:
        creates: /etc/letsencrypt/live/{{ domain }}/fullchain.pem

    - name: Fix letsencrypt permissions
      file:
        path: /etc/letsencrypt
        state: directory
        recurse: yes
        mode: '0755'

    - name: Deploy docker-compose
      command: docker-compose -f {{ repo_dest }}/docker-compose.yml up -d --build
      args:
        chdir: "{{ repo_dest }}"

    - name: Cron certbot renew
      cron:
        name: "Certbot renew"
        minute: "0"
        hour: "3"
        job: "certbot renew --quiet && docker restart pasta-nginx"